
import Script from "next/script";
import "@/sass/main.scss"; 
import Navigation from "@/components/layout/navigation"; 

export const metadata = {
  title: 'Natours | Exciting Tours',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
     
        <link rel="stylesheet" href="../../public/icon_font.css" />
      </head>
      <body>
        
       
        <Navigation /> 

        {children}
        
        <Script 
          src="https://checkout.razorpay.com/v1/checkout.js" 
          strategy="lazyOnload" 
        />
      </body>
    </html>
  );
}